-- ==============================================================================
-- SafeRide AI — Supabase & PostgreSQL Master Database Schema
-- ==============================================================================
-- Paste this entire script into your Supabase SQL Editor (Dashboard -> SQL Editor)
-- and click "RUN" to create all required tables, indexes, security policies, and
-- enable Supabase Realtime replication.
-- ==============================================================================

-- 1. INCIDENTS TABLE
CREATE TABLE IF NOT EXISTS public.incidents (
    incident_id TEXT PRIMARY KEY,
    timestamp TEXT NOT NULL,
    vehicle_type TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    rider_status TEXT NOT NULL DEFAULT 'PENDING_CHECK',
    language TEXT NOT NULL DEFAULT 'Telugu',
    message TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT 'REPORTED',
    address TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. INCIDENT MESSAGES (COMMUNICATION THREADS) TABLE
CREATE TABLE IF NOT EXISTS public.incident_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id TEXT NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    sender TEXT NOT NULL,
    original_text TEXT NOT NULL,
    translated_text TEXT DEFAULT '',
    timestamp TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TELEMETRY STREAM LOGS TABLE
CREATE TABLE IF NOT EXISTS public.telemetry_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id TEXT REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    speed DOUBLE PRECISION DEFAULT 0.0,
    g_force DOUBLE PRECISION DEFAULT 1.0,
    tilt_angle DOUBLE PRECISION DEFAULT 0.0,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- INDEXES FOR HIGH-PERFORMANCE QUERYING
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_incidents_timestamp ON public.incidents (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON public.incidents (status);
CREATE INDEX IF NOT EXISTS idx_messages_incident_id ON public.incident_messages (incident_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_incident_id ON public.telemetry_logs (incident_id);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
-- Enable RLS on all tables
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incident_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_logs ENABLE ROW LEVEL SECURITY;

-- Allow public access via anon key and authenticated users for real-time mobile integration
DROP POLICY IF EXISTS "Allow public read incidents" ON public.incidents;
CREATE POLICY "Allow public read incidents" 
ON public.incidents FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow public insert incidents" ON public.incidents;
CREATE POLICY "Allow public insert incidents" 
ON public.incidents FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update incidents" ON public.incidents;
CREATE POLICY "Allow public update incidents" 
ON public.incidents FOR UPDATE 
USING (true);

DROP POLICY IF EXISTS "Allow public read messages" ON public.incident_messages;
CREATE POLICY "Allow public read messages" 
ON public.incident_messages FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow public insert messages" ON public.incident_messages;
CREATE POLICY "Allow public insert messages" 
ON public.incident_messages FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read telemetry" ON public.telemetry_logs;
CREATE POLICY "Allow public read telemetry" 
ON public.telemetry_logs FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow public insert telemetry" ON public.telemetry_logs;
CREATE POLICY "Allow public insert telemetry" 
ON public.telemetry_logs FOR INSERT 
WITH CHECK (true);

-- ==============================================================================
-- SUPABASE REALTIME CONFIGURATION
-- ==============================================================================
-- Enable real-time websocket broadcasting for instant emergency alerts
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'incidents'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.incidents;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'incident_messages'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.incident_messages;
    END IF;
END $$;

-- ==============================================================================
-- SEED SAMPLE DEMO DATA (OPTIONAL INITIAL DATA)
-- ==============================================================================
INSERT INTO public.incidents (incident_id, timestamp, vehicle_type, latitude, longitude, confidence, rider_status, language, message, status, address)
VALUES 
    ('INC-2026-HYD-001', '2026-09-07 10:15:20', 'Motorcycle', 17.4435, 78.3772, 89.0, 'NEED HELP', 'Telugu', 'నాకు సహాయం కావాలి, కాలు విరిగింది (I need help, leg is broken)', 'REPORTED', '12 MG Road, Bengaluru'),
    ('INC-2026-BLR-002', '2026-09-07 09:30:45', 'Motorcycle', 12.9716, 77.5946, 94.5, 'NO RESPONSE', 'English', 'High impact crash detected. Rider unresponsive.', 'DISPATCHED', 'Residency Road Junction, Bengaluru'),
    ('INC-2026-CHE-003', '2026-09-06 18:40:12', 'Auto-Rickshaw', 13.0827, 80.2707, 78.0, 'NORMAL', 'English', 'Minor vehicle collision. All occupants safe.', 'RESOLVED', 'Anna Salai, Chennai'),
    ('INC-2026-MUM-004', '2026-09-06 14:22:00', 'Car', 19.0760, 72.8777, 85.0, 'NEED HELP', 'Telugu', 'కారు పల్టీ కొట్టింది, దయచేసి అంబులెన్స్ పంపండి (Car rolled over, please send ambulance)', 'DISPATCHED', 'Western Express Highway, Mumbai')
ON CONFLICT (incident_id) DO NOTHING;

INSERT INTO public.incident_messages (incident_id, sender, original_text, translated_text, timestamp)
VALUES
    ('INC-2026-HYD-001', 'Rider', 'నాకు సహాయం కావాలి, కాలు విరిగింది', 'I need help, leg is broken', '2026-09-07 10:15:20'),
    ('INC-2026-HYD-001', 'Responder', 'We have dispatched unit 108 to your location. Stay calm.', 'మేము మీ స్థానానికి 108 విభాగాన్ని పంపాము. ప్రశాంతంగా ఉండండి.', '2026-09-07 10:16:05'),
    ('INC-2026-BLR-002', 'System', 'Automated 10s SOS countdown expired. Emergency dispatch triggered via Twilio.', '', '2026-09-07 09:30:55')
ON CONFLICT DO NOTHING;
